### ISSUE TITLE
Issue building in UE 5.4

### ISSUE THREAD

**Issue by nick-bithead** [gtreshchev/AndroidNative#10]
Hello, I'm having issues compiling/building my project in Unreal 5.4 using this plugin, this is the issue I see: 

```
[176/187] Link [x64] UnrealEditor-AndroidNative.dll
error LNK2005: "class _jobject * FJavaWrapper::GameActivityThis" (?GameActivityThis@FJavaWrapper@@3PEAV_jobject@@EA) already defined in AndroidNativeLibrary.cpp.obj
```

Not sure why this is happening, FJavaWrapper::GameActivityThis is only defined once in JavaConvert.h but it is saying it is also defined in AndroidNativeLibrary.cpp for some reason, I see it being used there but not defined? 

I will continue investigating this issue, I did modify your plugin a little, I only needed it to be able to write my own Android Java functions and have them run in my Unreal project, so I removed most of the functions in AndroidNativeLibrary and replaced with my own, but none of them define GameActivityThis

**Comment by gtreshchev** [comment]
Hi, I guess it's not relevant anymore, as we discussed in Discord?

**Comment by nick-bithead** [comment]
Yes this is now working - just needed a fresh pull of the repository (I hadn't updated to the latest push from 3 months ago) 

Thanks for the help @gtreshchev !
