### ISSUE TITLE
I want to return TArray,

### ISSUE THREAD

**Issue by jiangzhiyu1016** [gtreshchev/AndroidNative#2]
![image](https://user-images.githubusercontent.com/56686900/162739187-2d9f5ae3-d232-4c03-be10-f7d408dfc136.png)

I want to return TArray<FString>, but that's the wrong way to write it. Can anyone tell me the correct way to write it? Thank you

**Comment by gtreshchev** [comment]
There was a small bug with the array. Should be fixed. Thanks for reporting.
