### ISSUE TITLE
Where to place the java class for the final build.

### ISSUE THREAD

**Issue by shive1807** [gtreshchev/AndroidNative#8]
I am unable to get where to place the StringOperation.java class inside the unreal project ? 

 java.lang.ClassNotFoundException: Didn't find class "com/Plugins/AndroidNative/StringOperations" on path: DexPathList[[zip file "/data/app/com.YourCompany.NativeUnrealLatest-4N0HniWBYF7SOqv9OSVQeQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.YourCompany.NativeUnrealLatest-4N0HniWBYF7SOqv9OSVQeQ==/lib/arm64, /data/app/com.YourCompany.NativeUnrealLatest-4N0HniWBYF7SOqv9OSVQeQ==/base.apk!/lib/arm64-v8a, /system/lib64]]at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:169)
 
 This is the error I am facing.

**Comment by gtreshchev** [comment]
You should add this file within the plugin itself, [here](https://github.com/gtreshchev/AndroidNative/tree/main/Source/AndroidNative/Private/Java). After doing so, you should be able to successfully call that function.

Also, in some cases, it is necessary to delete the Intermediate and Binaries folders of both the project and the plugin to ensure the Java classes are up to date, as mentioned on [this page](https://github.com/gtreshchev/AndroidNative/wiki/4.-Troubleshooting).
