### ISSUE TITLE
ue5.4

### ISSUE THREAD

**Issue by 444cilya444** [gtreshchev/AndroidNative#9]
When will ue5.4 be supported?

**Comment by gtreshchev** [comment]
UE 5.4 is supported. Do you have any issues when running the plugin on this engine version?

**Comment by 444cilya444** [comment]
Yes, but it's easier for you to download this version and see for yourself, because there are a lot of errors coming out

**Comment by gtreshchev** [comment]
I wasn't able to reproduce any errors. Can you pls share your logs?

**Comment by 444cilya444** [comment]
I'm sorry, but I've already deleted this version of the engine. But there were errors mainly related to the obsolescence of methods

**Comment by 444cilya444** [comment]
The problem arises precisely with my version of the plugin, since I added my own functionality there.

**Comment by gtreshchev** [comment]
I can recommend ensuring you update the plugin to the latest version, especially that you have this commit: https://github.com/gtreshchev/AndroidNative/commit/cb0cc3ef2e69face1168a952fbc37653a4d74eeb
